[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules","lib"]
test = "test"
cache_path = "forge-cache"
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
evm_version ="shanghai"
[invariant]
fail_on_revert = true
eth-rpc-url = "https://mainnet.infura.io/v3/ENTER_YOUR_KEY"
fs_permissions = [{ access = "read-write", path = "./"}]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[fuzz]
runs = 200
[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/ENTER_YOUR_KEY"
arbitrum = "https://arbitrum-mainnet.infura.io/v3/ENTER_YOUR_KEY"
